  
language: node_js
node_js:
  - 12
branches:
  only: master
cache:
  directories:
  - node_modules
script:
  - yarn build
  - yarn lint
  - yarn test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master