  
language: node_js
node_js:
  - 12
branches:
  only: master
cache:
  directories:
  - node_modules
script:
  - yarn build
  - yarn lint
  - yarn test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 167398e26fb11b2c95ca0677f3024714b346feec
  on:
    branch: master