  
language: node_js
node_js:
  - 12
branches:
  only: master
cache:
  directories:
  - node_modules
script:
  - yarn lint
  - yarn test
  - yarn build
deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master